name: Update site
on:
  push:
    branches: [ master ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Build
        run: |
          cd $GITHUB_WORKSPACE
          python3 install_deps.py
          python3 proof.py inklecate_v0.8.3 inklecate_v0.9.0 inklecate_v1.0.0 inklecate_v1.1.1 inklecate_v0.9.0+_runtime inklecate_v1.0.0_runtime inklecate_v1.1.1_runtime inkjs_v1.11.0_runtime inkjs_v1.10.5_runtime inkjs_v1.9.0_runtime inkjs_v2.0.0_runtime inkjs_v2.1.0_runtime inkjs_v2.2.0_runtime inkjs_v2.2.1_runtime inkjs_v2.2.1 || true
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          branch: gh-pages
          folder: out
